version: '3.8'

services:
  frontend:
    build:
      context: ./Client
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    environment:
      - NODE_ENV=development
    depends_on:
      - backend 
    volumes:
      - ./Client:/app
      - /app/node_modules
    # command: npm run dev

  backend:
    build:
      context: ./Server
      dockerfile: Dockerfile
    ports:
      - 4654:4654 
    environment:
      - NODE_ENV=development
      - MONGO_URL=mongodb://mongo:27017/go-org-repos 
      - GITHUB_API_TOKEN=${GITHUB_API_TOKEN}
    env_file: ./.docker.env
    depends_on:
      - mongo 
    volumes:
      - ./Server:/app
      - /app/node_modules

  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017" 
    volumes:
      - mongo-data:/data/db 

volumes:
  mongo-data:
    driver: local
